version: "3.9"

services:
  youtube_project:
    image: yt_django:latest
    container_name: yt_django
    volumes:
      - static_volume:/yt/static
      - media_volume:/yt/media
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate  && ./manage.py runserver 0.0.0.0:8000"