# Generated by Django 4.1 on 2022-09-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_homework', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='amount_day',
        ),
    ]
