# Generated by Django 4.1 on 2022-08-21 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_lancen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения занятия')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий (в случае необходимости)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lancen.learinggroup', verbose_name='Для какой группы')),
            ],
            options={
                'verbose_name': 'Расписание занятия группы',
                'verbose_name_plural': 'Расписание занятий групп',
            },
        ),
    ]
