# Generated by Django 4.1 on 2024-04-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='canceled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Отмена'),
        ),
    ]
