# Generated by Django 4.1 on 2024-04-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_timetable', '0002_timetable_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='canceled',
            field=models.BooleanField(blank=True, default=False, verbose_name='Отмена'),
        ),
    ]
