# Generated by Django 4.1 on 2024-04-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_timetable', '0003_alter_timetable_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='canceled',
            field=models.BooleanField(blank=True, default=False, verbose_name='Отмена (x - отмены нет)'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
