# Generated by Django 4.1 on 2024-04-09 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_abonements', '0004_discount'),
        ('app_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_born',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_abonements.discount', verbose_name='Скидка'),
        ),
    ]
