# Generated by Django 4.1 on 2022-08-21 18:16

import app_lancen.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название абонемента')),
                ('amount_lesson', models.IntegerField(verbose_name='Кол-во занятий')),
                ('price', models.IntegerField(verbose_name='Стоимость абонемента (руб.)')),
                ('duration', models.CharField(max_length=255, verbose_name='Продолжительность 1 занятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to=app_lancen.models.get_file_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.CreateModel(
            name='PaymentAbonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата старта абонемента')),
                ('date_payment', models.DateField(verbose_name='Дата оплаты абонемента абонемента')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Скидка в рублях (если есть)')),
                ('abonement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abonements.abonement', verbose_name='Какой абонемент')),
            ],
            options={
                'verbose_name': 'Оплата абонемента',
                'verbose_name_plural': 'Оплаты абонементов',
            },
        ),
        migrations.CreateModel(
            name='StudentPaymenatLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_timetable.timetable', verbose_name='К какому уроку ')),
                ('payment_abonement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abonements.paymentabonement', verbose_name='К какой оплате студента')),
            ],
            options={
                'verbose_name': 'Оплаченное занятие пользователя',
                'verbose_name_plural': 'Оплаченные занятия пользователя',
            },
        ),
    ]
