# Generated by Django 4.1 on 2022-08-21 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_abonements', '0001_initial'),
        ('app_profiles', '0001_initial'),
        ('app_lancen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentabonement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_profiles.student', verbose_name='Какой студент'),
        ),
        migrations.AddField(
            model_name='abonement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lancen.trainingprogramm', verbose_name='К какому курсу'),
        ),
    ]
