# Generated by Django 4.1 on 2022-10-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lancen', '0001_initial'),
        ('app_abonements', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonement',
            name='course',
        ),
        migrations.AddField(
            model_name='abonement',
            name='course',
            field=models.ManyToManyField(related_name='abonement_courses', to='app_lancen.trainingprogramm', verbose_name='К какому курсу'),
        ),
    ]
