# Generated by Django 4.1 on 2024-04-24 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_abonements', '0004_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentabonement',
            name='discount',
        ),
    ]
