# Generated by Django 4.1 on 2022-10-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='behavior',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10)], verbose_name='Поведение'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='extra',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10)], verbose_name='EXTRA'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='homework',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10)], verbose_name='Домашнее задание'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='work_on_lesson',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10)], verbose_name='Работа на уроке'),
        ),
    ]
